// File generated by FlutterFire CLI.
// This is a placeholder - you need to run 'flutterfire configure' to generate actual Firebase configuration

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // You need to run: flutterfire configure
    // This will generate the actual configuration
    throw UnimplementedError(
      'DefaultFirebaseOptions have not been configured for this platform.\n'
      'Please run: flutterfire configure',
    );
  }
}

class FirebaseOptions {
  const FirebaseOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    this.authDomain,
    this.databaseURL,
    this.storageBucket,
    this.measurementId,
    this.trackingId,
    this.deepLinkURLScheme,
    this.androidClientId,
    this.iosClientId,
    this.iosBundleId,
    this.appGroupId,
  });

  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String? authDomain;
  final String? databaseURL;
  final String? storageBucket;
  final String? measurementId;
  final String? trackingId;
  final String? deepLinkURLScheme;
  final String? androidClientId;
  final String? iosClientId;
  final String? iosBundleId;
  final String? appGroupId;
}

